version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    reviewers:
      - Rygent
