version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    reviewers:
      - Rygent
    ignore:
      - dependency-name: "chalk"
        versions: ["5.x"]
