name: Bug report
description: Report incorrect or unexpected behavior
labels: [bug, need repro]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/FD5MMabf8Y
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce:
        1. do thing
        2. do thing in Discord client
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: input
    id: djs-version
    attributes:
      label: Discord.JS version
      description: Which version of Discord.JS are you using? Run `yarn why discord.js` in your project directory and paste the output.
      placeholder: Discord.JS version 13.x.x
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.JS version
      description: Which version of Node.JS are you using? Run `node --version` in your project directory and paste the output.
      placeholder: Node.JS version 16.6+
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true