name: Bug report
description: Report incorrect or unexpected behavior of Elvia
title: 'Bug: <title>'
labels: [bug, help wanted]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/FD5MMabf8Y
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        2. do thing in Discord client
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: textarea
    id: codesample
    attributes:
      label: Codesample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: typescript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem
  - type: input
    id: djs-version
    attributes:
      label: Discord.JS version
      description: Which version of discord.js are you using? Run `npm list discord.js` in your project directory and paste the output.
      placeholder: Discord.js version 13.x.x
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.JS version
      description: Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
      placeholder: Node.js version 16.6+ is required
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
  - type: dropdown
    id: intents
    attributes:
      label: Which gateway intents are you subscribing to?
      description: |
        Check your Client constructor for the `intents` key.

        Tip: you can select multiple items
      options:
        - GUILDS
        - GUILD_MEMBERS
        - GUILD_BANS
        - GUILD_EMOJIS_AND_STICKERS
        - GUILD_INTEGRATIONS
        - GUILD_WEBHOOKS
        - GUILD_INVITES
        - GUILD_VOICE_STATES
        - GUILD_PRESENCES
        - GUILD_MESSAGES
        - GUILD_MESSAGE_REACTIONS
        - GUILD_MESSAGE_TYPING
        - DIRECT_MESSAGES
        - DIRECT_MESSAGE_REACTIONS
        - DIRECT_MESSAGE_TYPING
        - GUILD_SCHEDULED_EVENTS
      multiple: true
    validations:
      required: true